SET HEADING OFF
SET LINES 200
SET PAGES 2000
COLUMN TEXT FORMAT A200
ACCEPT PAQUETE PROMPT "Nombre paquete: "
SPOOL &&PAQUETE..s.sql
SELECT TEXT 
FROM   USER_SOURCE
WHERE  NAME = UPPER( '&&PAQUETE' )
  AND  TYPE = 'PACKAGE'
ORDER  BY LINE
/
SPOOL OFF
SPOOL &&PAQUETE..b.sql
SELECT TEXT 
FROM   USER_SOURCE
WHERE  NAME = UPPER( '&&PAQUETE' )
  AND  TYPE = 'PACKAGE BODY'
ORDER  BY LINE
/
SPOOL OFF
