COLUMN FILE_NAME FORMAT A30
COLUMN TABLESPACE_NAME FORMAT A30
SELECT TABLESPACE_NAME, FILE_NAME, ROUND( BYTES/1024/1024, 2 ) MEGAS
FROM DBA_DATA_FILES
ORDER BY TABLESPACE_NAME
/
SELECT TABLESPACE_NAME, FILE_NAME, ROUND( BYTES/1024/1024,2) MEGAS, AUTOEXTENSIBLE
FROM DBA_TEMP_FILES
ORDER BY TABLESPACE_NAME
/