SET LONG 5000
execute DBMS_METADATA.SET_TRANSFORM_PARAM( DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',true);

execute DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',true);
SELECT DBMS_METADATA.get_DDL( OBJECT_TYPE, OBJECT_NAME, USER )
FROM USER_OBJECTS
WHERE OBJECT_NAME = UPPER('&MASCARA')
and object_type not in ('PACKAGE BODY')
/
