SET LONG 500
SET LINES 800
PROMPT LISTA DE FK FORÁNEAS
SELECT R_CONSTRAINT_NAME, TABLE_NAME
FROM   USER_CONSTRAINTS R
WHERE  R_OWNER != USER 
ORDER BY R_CONSTRAINT_NAME
/
PROMPT DDL DE CONSTRAINTS A OTROS ESQUEMAS
SELECT DBMS_METADATA.get_DDL('REF_CONSTRAINT',r.CONSTRAINT_NAME, r.OWNER ) DEFI
FROM   USER_CONSTRAINTS R
WHERE  R_OWNER != USER 
ORDER BY TABLE_NAME
/
