-- Script que lista los índices de una tabla y sus columnas
ACCEPT TABLA PROMPT "Nombre de la tabla: "
COLUMN COLUMN_NAME FORMAT A30
BREAK ON INDEX_NAME
SET VERIFY OFF
SELECT INDEX_NAME, COLUMN_NAME, DESCEND
FROM   USER_IND_COLUMNS
WHERE  TABLE_NAME = UPPER('&&TABLA')
ORDER BY INDEX_NAME, COLUMN_POSITION
/
SET VERIFY ON
