-- login.sql
-- Sección set
SET PAGES 10000
SET LINES 150
SET TIME ON
SET TIMING ON
SET TRIMOUT ON
SET SERVEROUTPUT ON
-- Columnas para alias en las selects
COLUMN TOTAL FORMAT 999,999,990.00
SHOW USER

